#
#	Copyright abandoned, 1983, The Rand Corporation
#

# Rand Editor with LA package
# The following groups go together
#   CFLAGS=-g and LIBC=-lg for debugging on the VAX
#   DEFS=-DTERMCAP and TERMCAP=-ltermcap
#   DEFS=-DPROFILE and PROFILE=-p
#

DFS     = -DUNIXV7 -DTERMCAP
CCF     = -g -traditional
LDF     = -g
LD      = gcc
CC      = gcc

LOCALINCL = ../include
LA      = ../la1/
LALIB   = ../la1/libla.a
FF      = ../ff3/
FFLIB   = ../ff3/libff.a
MISC    = ../lib
MISCLIB = ../lib/libtmp.a
DEFS    = $(DFS)
# NEWVERSION creates e.r.c
NEWVERSION = newversion
INCL    = -I. -I$(LA) -I$(FF) -I$(LOCALINCL)
SIG_INCL =signal.h
SGTT_INCL =sgtty.h
CFLAGS  = $(CCF) $(DEFS) $(INCL) $(PROFILE)
LDFLAGS = $(LDF)
RM      = rm -f
LIBS    = $(LALIB) $(FFLIB) -ltermcap

HFILES  = \
	e.cm.h \
	e.e.h \
	e.fn.h \
	e.func.h \
	e.h \
	e.inf.h \
	e.m.h \
	e.ru.h \
	e.se.h \
	e.sg.h \
	e.t.h \
	e.tt.h \
	e.wi.h

OFILES  = \
	e.o \
	e.cm.o \
	e.d.o \
	e.e.o \
	e.f.o \
	e.h.o \
	e.iit.o \
	e.it.o \
	e.la.o \
	e.m.o \
	e.main.o \
	e.mk.o \
	e.nm.o \
	e.p.o \
	e.pa.o \
	e.profile.o \
	e.put.o \
	e.q.o \
	e.ra.o \
	e.re.o \
	e.ru.o \
	e.sb.o \
	e.se.o \
	e.sv.o \
	e.t.o \
	e.tb.o \
	e.tt.o \
	e.u.o \
	e.wi.o \
	e.wk.o \
	e.x.o \
	getshort.o \
	getlong.o  \
	putshort.o \
	putlong.o

CFILES  = \
	e.c \
	e.cm.c \
	e.d.c \
	e.e.c \
	e.f.c \
	e.h.c \
	e.iit.c \
	e.it.c \
	e.la.c \
	e.m.c \
	e.main.c \
	e.mk.c \
	e.nm.c \
	e.p.c \
	e.pa.c \
	e.profile.c \
	e.put.c \
	e.q.c \
	e.r.c \
	e.ra.c \
	e.re.c \
	e.ru.c \
	e.sb.c \
	e.se.c \
	e.sv.c \
	e.t.c \
	e.tb.c \
	e.tt.c \
	e.u.c \
	e.wi.c \
	e.wk.c \
	e.x.c \
	getshort.c \
	getlong.c  \
	putshort.c \
	putlong.c

nle:     $(OFILES)
	/bin/sh $(NEWVERSION)
	$(CC) $(CFLAGS) -c e.r.c
	$(LD) -o nle $(LDFLAGS) $(OFILES) e.r.o $(LIBS)

ofiles: $(OFILES)

newrev:
	/bin/sh $(NEWVERSION)
	$(CC) $(CFLAGS) -c e.r.c

$(LALIB):

$(FFLIB):

$(MISCLIB):

# Be sure the defs in "Ifdefs" agree with $(DEFS)
depend:
	makedepend $(CFLAGS) $(HFILES) $(CFILES)

# Be sure the defs in "Ifdefs" agree with $(DEFS)
Comments: $(CFILES)
	Makedoc $(CFILES)

# Be sure the defs in "Ifdefs" agree with $(DEFS)
Calls:  $(CFILES)
	Makecalls $(CFILES)

lint:
	lint $(DEFS) $(INCL) $(CFILES) \
        $(FF)llib-lff.ln \
        $(LA)llib-lla.ln \
	-lc

pres: pres.o $(MISCLIB)
	$(CC)        \
	pres.o \
	$(MISCLIB)
	-mv pres pres.old
	mv a.out pres

clobber:      clean
	$(RM) nle pres pres.old ,* .??*
clean:
	$(RM) $(OFILES) pres.o

# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
# DO NOT DELETE THIS LINE -- make depend depends on it.

e.o: ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.o: /usr/include/_G_config.h e.t.h
e.sg.o: /usr/include/sys/ioctl.h /usr/include/linux/ioctl.h
e.sg.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.sg.o: /usr/include/sys/termios.h
e.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.o: /usr/include/_G_config.h e.t.h e.e.h e.tt.h e.wi.h e.fn.h e.sg.h
e.o: /usr/include/sys/ioctl.h /usr/include/linux/ioctl.h
e.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.o: /usr/include/sys/termios.h e.inf.h /usr/include/sys/stat.h
e.o: /usr/include/linux/stat.h
e.cm.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.cm.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.cm.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.cm.o: /usr/include/_G_config.h e.t.h e.e.h e.m.h e.ru.h e.cm.h e.wi.h
e.cm.o: e.tt.h
e.d.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.d.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.d.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.d.o: /usr/include/_G_config.h e.t.h e.tt.h
e.e.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.e.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.e.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.e.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h e.e.h
e.f.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.f.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.f.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.f.o: /usr/include/_G_config.h e.t.h /usr/include/sys/stat.h
e.f.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.f.o: /usr/include/linux/stat.h
e.h.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.h.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.h.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.h.o: /usr/include/_G_config.h e.t.h e.cm.h e.m.h e.tt.h e.h.h
e.iit.o: e.h ../include/c_env.h ../include/localenv.h
e.iit.o: /usr/include/sys/types.h /usr/include/linux/types.h
e.iit.o: /usr/include/asm/types.h ../la1/la.h ../ff3/ff.h
e.iit.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
e.iit.o: e.t.h
e.it.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.it.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.it.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.it.o: /usr/include/_G_config.h e.t.h
e.la.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.la.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.la.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.la.o: /usr/include/_G_config.h e.t.h e.m.h
e.m.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.m.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.m.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.m.o: /usr/include/_G_config.h e.t.h e.cm.h e.inf.h e.m.h e.tt.h e.e.h
e.main.o: e.h ../include/c_env.h ../include/localenv.h
e.main.o: /usr/include/sys/types.h /usr/include/linux/types.h
e.main.o: /usr/include/asm/types.h ../la1/la.h ../ff3/ff.h
e.main.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
e.main.o: e.t.h
e.mk.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.mk.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.mk.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.mk.o: /usr/include/_G_config.h e.t.h e.inf.h e.m.h
e.nm.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.nm.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.nm.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.nm.o: /usr/include/_G_config.h e.t.h e.inf.h e.m.h e.cm.h
e.nm.o: /usr/include/sys/stat.h /usr/include/features.h
e.nm.o: /usr/include/sys/cdefs.h /usr/include/linux/stat.h
e.p.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.p.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.p.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.p.o: /usr/include/_G_config.h e.t.h e.cm.h e.inf.h e.m.h
e.p.o: /usr/include/ctype.h /usr/include/features.h /usr/include/sys/cdefs.h
e.pa.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.pa.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.pa.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.pa.o: /usr/include/_G_config.h e.t.h /usr/include/ctype.h
e.pa.o: /usr/include/features.h /usr/include/sys/cdefs.h e.m.h e.cm.h
e.profile.o: e.h ../include/c_env.h ../include/localenv.h
e.profile.o: /usr/include/sys/types.h /usr/include/linux/types.h
e.profile.o: /usr/include/asm/types.h ../la1/la.h ../ff3/ff.h
e.profile.o: /usr/include/stdio.h /usr/include/libio.h
e.profile.o: /usr/include/_G_config.h e.t.h e.m.h /usr/include/sys/stat.h
e.profile.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.profile.o: /usr/include/linux/stat.h e.tt.h
e.put.o: e.h ../include/c_env.h ../include/localenv.h
e.put.o: /usr/include/sys/types.h /usr/include/linux/types.h
e.put.o: /usr/include/asm/types.h ../la1/la.h ../ff3/ff.h
e.put.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
e.put.o: e.t.h e.m.h e.cm.h e.e.h
e.q.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.q.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.q.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.q.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h e.fn.h e.tt.h
e.ra.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.ra.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.ra.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.ra.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h
e.re.o: /usr/include/ctype.h /usr/include/features.h /usr/include/sys/cdefs.h
e.re.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.re.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.re.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.re.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h e.se.h
e.ru.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.ru.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.ru.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.ru.o: /usr/include/_G_config.h e.t.h e.e.h e.m.h e.cm.h e.ru.h
e.sb.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.sb.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.sb.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.sb.o: /usr/include/_G_config.h e.t.h e.fn.h e.sg.h /usr/include/sys/ioctl.h
e.sb.o: /usr/include/linux/ioctl.h /usr/include/features.h
e.sb.o: /usr/include/sys/cdefs.h /usr/include/sys/termios.h
e.sb.o: /usr/include/pwd.h /usr/include/gnu/types.h /usr/include/sys/stat.h
e.sb.o: /usr/include/linux/stat.h
e.se.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.se.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.se.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.se.o: /usr/include/_G_config.h e.t.h /usr/include/ctype.h
e.se.o: /usr/include/features.h /usr/include/sys/cdefs.h e.m.h e.cm.h e.se.h
e.sv.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.sv.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.sv.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.sv.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h /usr/include/sys/stat.h
e.sv.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.sv.o: /usr/include/linux/stat.h
e.t.o: ../include/varargs.h e.h ../include/c_env.h ../include/localenv.h
e.t.o: /usr/include/sys/types.h /usr/include/linux/types.h
e.t.o: /usr/include/asm/types.h ../la1/la.h ../ff3/ff.h /usr/include/stdio.h
e.t.o: /usr/include/libio.h /usr/include/_G_config.h e.t.h e.inf.h e.m.h
e.t.o: e.tt.h e.wi.h
e.tb.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.tb.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.tb.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.tb.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h
e.tt.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.tt.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.tt.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.tt.o: /usr/include/_G_config.h e.t.h e.tt.h e.sg.h /usr/include/sys/ioctl.h
e.tt.o: /usr/include/linux/ioctl.h /usr/include/features.h
e.tt.o: /usr/include/sys/cdefs.h /usr/include/sys/termios.h term/standard.c
e.tt.o: term/tcap.c term/vt100.c term/vt52.c term/sun.c term/xterm.c
e.u.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.u.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.u.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.u.o: /usr/include/_G_config.h e.t.h e.m.h e.cm.h /usr/include/sys/stat.h
e.u.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.u.o: /usr/include/linux/stat.h /usr/include/pwd.h /usr/include/gnu/types.h
e.wi.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.wi.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.wi.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.wi.o: /usr/include/_G_config.h e.t.h e.cm.h e.inf.h e.tt.h e.wi.h
e.wk.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.wk.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.wk.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.wk.o: /usr/include/_G_config.h e.t.h e.inf.h
e.x.o: e.h ../include/c_env.h ../include/localenv.h /usr/include/sys/types.h
e.x.o: /usr/include/linux/types.h /usr/include/asm/types.h ../la1/la.h
e.x.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
e.x.o: /usr/include/_G_config.h e.t.h e.e.h e.inf.h e.m.h e.sg.h
e.x.o: /usr/include/sys/ioctl.h /usr/include/linux/ioctl.h
e.x.o: /usr/include/features.h /usr/include/sys/cdefs.h
e.x.o: /usr/include/sys/termios.h
getshort.o: ../include/localenv.h /usr/include/stdio.h /usr/include/libio.h
getshort.o: /usr/include/_G_config.h
getlong.o: ../include/localenv.h /usr/include/stdio.h /usr/include/libio.h
getlong.o: /usr/include/_G_config.h
putshort.o: /usr/include/stdio.h /usr/include/libio.h
putshort.o: /usr/include/_G_config.h
putlong.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
